# Learning Numpy

In [2]:
import numpy as np 

### Creating Arrays

<strong><ins>All arrays mentioned here are numpy arrays as long as opposite is not mentioned</ins></strong> please solve the problems with this knowledge.

Create an array in size of 4*3 and assing it to arr variable 

In [22]:
arr = np.ndarray(shape=(3,4))

arr.ndim

2

Create an array with elements from 0 to 15 (both inclusive) and assing it to arr2 variable   
Then print the shape of the arr2  
copy the arr2 to arr2_copy  
print arr2, arr2_copy   
Change its shape to 4*4 and assign to itself   
print arr2, arr2_copy again    

In [14]:
arr2 = np.arange(16)
print('shape of arr2',arr2.shape)
arr2_copy = arr2.copy()

shape of arr2 (16,)


In [15]:
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [12]:
print(arr2_copy)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [17]:
arr2 = arr2.reshape(4,4)

In [18]:
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [19]:
print(arr2_copy)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


### Some Functions 

##### How many dimentions there are in arr2 variable? 

In [21]:
arr2.ndim

2

##### Describe the number of rows and columns in arr2 variable 

In [23]:
arr2.shape

(4, 4)

##### How many elements there are in arr2 variable?

In [24]:
arr2.size

16

##### Print the data type of arr2

In [27]:
arr2.dtype

dtype('int32')

#### Print the data location in the memory

In [28]:
arr2.data

### Some Statistics About the Arrays

#### Show 50th percentile of arr2

In [32]:
np.percentile(arr2,50)

7.5

#### Show mean of arr2 elements

In [30]:
arr2.mean()

7.5

#### Show median of arr2 elements

In [31]:
np.median(arr2)

7.5

##### Create one dimensional normally distrubuted array with mean 3 standard deviation is 4 and has elements of 100

In [34]:
from numpy import random

In [3]:
s = np.random.normal(loc=3,scale=4,size=100)

s

array([ 5.91476136,  0.24723583,  2.45179567,  1.68890586, -1.05986844,
       -3.26604751,  6.83934931,  4.87273231,  1.97574627,  5.65576001,
        1.05954629,  1.02439763, -2.151917  , -0.18666494,  3.34296816,
       -6.90049592, 10.31325235,  2.53911   ,  2.01125909,  7.63499553,
       -1.15329611,  5.8857308 ,  9.82462228, -1.97981364,  3.70661298,
       -1.82807692,  0.39626497, 12.01906204,  3.22183164,  6.48999902,
       -0.39863957,  1.20866022,  2.7363174 , -2.35878817, -0.7750026 ,
        3.09790226,  3.48059542, -1.47309588, -2.20482421,  3.3078272 ,
        4.96816513,  6.65681462, -1.79295908,  1.78102314,  4.704217  ,
        1.26024216,  1.288394  , -2.16167129,  2.87048131,  1.57187998,
        3.25972601,  4.61150202, -5.3545623 ,  2.69978435,  6.13415126,
       -0.54627633,  4.1404694 ,  2.67154997,  0.22453444,  4.60740343,
       -1.51125832, -1.2206293 , -1.06776863,  2.08120759, -2.60152645,
        0.25174509,  3.94238405,  4.79261908,  1.27268368, -0.24

#### Install matplotlib library for ploting purposes and then plot the s 
- search to find how to do

In [ ]:
# $$$$$
import matplotlib.pylab as plt

s.sum()

# plt.show()
_
_

____

# Learning Pandas

##### Read the airline safety data assign to df variable and print first 5 rows with pandas function

In [13]:
import pandas as pd 

In [14]:
df = pd.read_csv('./airline_safety_data.txt')

In [15]:
df.head(5)

airline  avail_seat_km_per_week  incidents_85_99  \
0             Aer Lingus               320906734                2   
1              Aeroflot*              1197672318               76   
2  Aerolineas Argentinas               385803648                6   
3            Aeromexico*               596871813                3   
4             Air Canada              1865253802                2   

   fatal_accidents_85_99  fatalities_85_99  incidents_00_14  \
0                      0                 0                0   
1                     14               128                6   
2                      0                 0                1   
3                      1                64                5   
4                      0                 0                2   

   fatal_accidents_00_14  fatalities_00_14  
0                      0                 0  
1                      1                88  
2                      0                 0  
3                      0                 0  
4                      0                 0

##### print last 5 rows with pandas function

In [38]:
df.tail(5)

airline  avail_seat_km_per_week  incidents_85_99  \
51       United / Continental*              7139291291               19   
52  US Airways / America West*              2455687887               16   
53            Vietnam Airlines               625084918                7   
54             Virgin Atlantic              1005248585                1   
55             Xiamen Airlines               430462962                9   

    fatal_accidents_85_99  fatalities_85_99  incidents_00_14  \
51                      8               319               14   
52                      7               224               11   
53                      3               171                1   
54                      0                 0                0   
55                      1                82                2   

    fatal_accidents_00_14  fatalities_00_14  
51                      2               109  
52                      2                23  
53                      0                 0  
54                      0                 0  
55                      0                 0

##### Show shape of df

In [39]:
df.shape

(56, 8)

##### Show descriptive statistics of df

In [40]:
df.describe()

avail_seat_km_per_week  incidents_85_99  fatal_accidents_85_99  \
count            5.600000e+01        56.000000              56.000000   
mean             1.384621e+09         7.178571               2.178571   
std              1.465317e+09        11.035656               2.861069   
min              2.593733e+08         0.000000               0.000000   
25%              4.740362e+08         2.000000               0.000000   
50%              8.029089e+08         4.000000               1.000000   
75%              1.847239e+09         8.000000               3.000000   
max              7.139291e+09        76.000000              14.000000   

       fatalities_85_99  incidents_00_14  fatal_accidents_00_14  \
count         56.000000        56.000000              56.000000   
mean         112.410714         4.125000               0.660714   
std          146.691114         4.544977               0.858684   
min            0.000000         0.000000               0.000000   
25%            0.000000         1.000000               0.000000   
50%           48.500000         3.000000               0.000000   
75%          184.250000         5.250000               1.000000   
max          535.000000        24.000000               3.000000   

       fatalities_00_14  
count         56.000000  
mean          55.517857  
std          111.332751  
min            0.000000  
25%            0.000000  
50%            0.000000  
75%           83.250000  
max          537.000000

#### Show df column informations

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   airline                 56 non-null     object
 1   avail_seat_km_per_week  56 non-null     int64 
 2   incidents_85_99         56 non-null     int64 
 3   fatal_accidents_85_99   56 non-null     int64 
 4   fatalities_85_99        56 non-null     int64 
 5   incidents_00_14         56 non-null     int64 
 6   fatal_accidents_00_14   56 non-null     int64 
 7   fatalities_00_14        56 non-null     int64 
dtypes: int64(7), object(1)
memory usage: 3.6+ KB


#### Select companies and incidents_85_99 with incidents_85_99 is less than 10

In [30]:
df[df['incidents_85_99']<10][['airline','incidents_85_99']]

airline  incidents_85_99
0               Aer Lingus                2
2    Aerolineas Argentinas                6
3              Aeromexico*                3
4               Air Canada                2
6               Air India*                2
7         Air New Zealand*                3
8         Alaska Airlines*                5
9                 Alitalia                7
10      All Nippon Airways                3
12       Austrian Airlines                1
13                 Avianca                5
14        British Airways*                4
15         Cathay Pacific*                0
17                  Condor                2
18                    COPA                3
20                Egyptair                8
21                   El Al                1
23                 Finnair                1
25                Gulf Air                1
26       Hawaiian Airlines                0
27                  Iberia                4
28          Japan Airlines                3
29           Kenya Airways                2
30                    KLM*                7
32            LAN Airlines                3
33              Lufthansa*                6
34       Malaysia Airlines                3
35  Pakistan International                8
36     Philippine Airlines                7
37                 Qantas*                1
38         Royal Air Maroc                5
39                    SAS*                5
40           Saudi Arabian                7
41      Singapore Airlines                2
42           South African                2
43      Southwest Airlines                1
44   Sri Lankan / AirLanka                2
45                  SWISS*                2
46                    TACA                3
47                     TAM                8
48      TAP - Air Portugal                0
49            Thai Airways                8
50        Turkish Airlines                8
53        Vietnam Airlines                7
54         Virgin Atlantic                1
55         Xiamen Airlines                9

#### Group companies by first letter(lower) and take the mean incidents_85_99 and make it a dataframe again 

In [ ]:
df.groupby(df['airline'].str[0])['incidents_85_99'].agg('mean')

In [ ]:
df_grouped=df.groupby(df['airline'].str[0])['incidents_85_99']\
                .agg('mean')\
                .copy()\
                .reset_index()

df_grouped